services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - MONGO_INITDB_DATABASE=something
      - MONGO_INITDB_ROOT_USERNAME=range79
      - MONGO_INITDB_ROOT_PASSWORD=testpw
    ports:
      - '27017:27017'

  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=range79
      - POSTGRES_PASSWORD=testpw
    ports:
      - '5432:5432'
